/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snJatakamAI;

import snJatakamAI.snJatakam.sn_Jatakam.snMatch;
public class App {

  public String getGreeting() {
    return "Hello World! This is snJatakam for Analytics using AI";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    snMatch snJM = new snMatch(args);
  }
}
